import { relations, sql } from "drizzle-orm";
import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Shared columns
// ---------------------------------------------------------------------------

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const memberRole = pgEnum("member_role", ["INSTRUCTOR", "TA", "STUDENT"]);
export const assignmentStatus = pgEnum("assignment_status", ["DRAFT", "PUBLISHED", "CLOSED"]);
export const submissionStatus = pgEnum("submission_status", ["DRAFT", "SUBMITTED"]);
export const aiRunStatus = pgEnum("ai_run_status", ["PENDING", "SUCCEEDED", "FAILED"]);
export const aiErrorCode = pgEnum("ai_error_code", [
  "TIMEOUT",
  "PROVIDER",
  "INVALID_OUTPUT",
  "CAP",
  "STALE",
]);
export const gradeStatus = pgEnum("grade_status", ["DRAFT", "RELEASED"]);
export const scoreSource = pgEnum("score_source", ["AI", "HUMAN", "AI_EDITED"]);
export const regradeStatus = pgEnum("regrade_status", ["OPEN", "ACCEPTED", "REJECTED"]);

// ---------------------------------------------------------------------------
// Auth (Better Auth core schema; text ids are generated by Better Auth)
// ---------------------------------------------------------------------------

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  ...timestamps,
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    token: text("token").notNull().unique(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    ...timestamps,
  },
  (t) => [index("session_user_id_idx").on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    password: text("password"),
    ...timestamps,
  },
  (t) => [index("account_user_id_idx").on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);

// Better Auth rate limiting, stored in Postgres so limits hold across serverless instances.
export const rateLimit = pgTable("rate_limit", {
  id: text("id").primaryKey(),
  key: text("key").notNull().unique(),
  count: integer("count").notNull(),
  lastRequest: bigint("last_request", { mode: "number" }).notNull(),
});

// ---------------------------------------------------------------------------
// Courses
// ---------------------------------------------------------------------------

export const course = pgTable("course", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: varchar("name", { length: 120 }).notNull(),
  description: varchar("description", { length: 1000 }),
  joinCode: varchar("join_code", { length: 12 }).notNull().unique(),
  aiEnabled: boolean("ai_enabled").notNull().default(true),
  createdBy: text("created_by")
    .notNull()
    .references(() => user.id, { onDelete: "restrict" }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  ...timestamps,
});

export const courseMember = pgTable(
  "course_member",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    role: memberRole("role").notNull(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("course_member_course_user_uq").on(t.courseId, t.userId),
    index("course_member_user_id_idx").on(t.userId),
  ],
);

// ---------------------------------------------------------------------------
// Assignments and rubrics
// ---------------------------------------------------------------------------

export const assignment = pgTable(
  "assignment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id, { onDelete: "restrict" }),
    title: varchar("title", { length: 120 }).notNull(),
    instructions: text("instructions").notNull().default(""),
    dueAt: timestamp("due_at", { withTimezone: true }).notNull(),
    allowLate: boolean("allow_late").notNull().default(false),
    status: assignmentStatus("status").notNull().default("DRAFT"),
    maxScore: integer("max_score").notNull().default(0),
    createdBy: text("created_by")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [
    index("assignment_course_id_idx").on(t.courseId),
    check("assignment_max_score_nonneg", sql`${t.maxScore} >= 0`),
  ],
);

export const rubricCriterion = pgTable(
  "rubric_criterion",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Cascade: a DRAFT assignment may be hard-deleted together with its rubric.
    assignmentId: uuid("assignment_id")
      .notNull()
      .references(() => assignment.id, { onDelete: "cascade" }),
    title: varchar("title", { length: 120 }).notNull(),
    description: varchar("description", { length: 1000 }).notNull().default(""),
    position: integer("position").notNull(),
    ...timestamps,
  },
  (t) => [index("rubric_criterion_assignment_id_idx").on(t.assignmentId)],
);

export const rubricLevel = pgTable(
  "rubric_level",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    criterionId: uuid("criterion_id")
      .notNull()
      .references(() => rubricCriterion.id, { onDelete: "cascade" }),
    label: varchar("label", { length: 60 }).notNull(),
    points: integer("points").notNull(),
    descriptor: varchar("descriptor", { length: 1000 }).notNull().default(""),
    position: integer("position").notNull(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("rubric_level_criterion_points_uq").on(t.criterionId, t.points),
    check("rubric_level_points_range", sql`${t.points} between 0 and 100`),
  ],
);

// ---------------------------------------------------------------------------
// Submissions
// ---------------------------------------------------------------------------

export const submission = pgTable(
  "submission",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Restrict: an assignment with submissions can never be hard-deleted.
    assignmentId: uuid("assignment_id")
      .notNull()
      .references(() => assignment.id, { onDelete: "restrict" }),
    studentId: text("student_id")
      .notNull()
      .references(() => user.id, { onDelete: "restrict" }),
    content: text("content").notNull().default(""),
    wordCount: integer("word_count").notNull().default(0),
    status: submissionStatus("status").notNull().default("DRAFT"),
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    isLate: boolean("is_late").notNull().default(false),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("submission_assignment_student_uq").on(t.assignmentId, t.studentId),
    index("submission_assignment_status_idx").on(t.assignmentId, t.status),
    index("submission_student_id_idx").on(t.studentId),
    check("submission_word_count_nonneg", sql`${t.wordCount} >= 0`),
  ],
);

// ---------------------------------------------------------------------------
// AI grading runs
// ---------------------------------------------------------------------------

export const aiGradingRun = pgTable(
  "ai_grading_run",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    submissionId: uuid("submission_id")
      .notNull()
      .references(() => submission.id, { onDelete: "cascade" }),
    // Denormalised so the per-course daily AI cap is a single indexed count.
    courseId: uuid("course_id")
      .notNull()
      .references(() => course.id, { onDelete: "cascade" }),
    requestedBy: text("requested_by").references(() => user.id, { onDelete: "set null" }),
    status: aiRunStatus("status").notNull().default("PENDING"),
    errorCode: aiErrorCode("error_code"),
    model: varchar("model", { length: 80 }).notNull(),
    promptVersion: varchar("prompt_version", { length: 20 }).notNull(),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    rawOutput: jsonb("raw_output"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("ai_run_submission_created_idx").on(t.submissionId, t.createdAt),
    index("ai_run_status_started_idx").on(t.status, t.startedAt),
    index("ai_run_course_created_idx").on(t.courseId, t.createdAt),
    // At most one active run per submission.
    uniqueIndex("ai_run_one_pending_per_submission_uq")
      .on(t.submissionId)
      .where(sql`${t.status} = 'PENDING'`),
  ],
);

// ---------------------------------------------------------------------------
// Grades
// ---------------------------------------------------------------------------

export const grade = pgTable(
  "grade",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    submissionId: uuid("submission_id")
      .notNull()
      .unique()
      .references(() => submission.id, { onDelete: "restrict" }),
    status: gradeStatus("status").notNull().default("DRAFT"),
    totalScore: integer("total_score").notNull().default(0),
    overallFeedback: text("overall_feedback").notNull().default(""),
    gradedBy: text("graded_by").references(() => user.id, { onDelete: "set null" }),
    releasedBy: text("released_by").references(() => user.id, { onDelete: "set null" }),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    // Optimistic locking: every save must match and increment this.
    version: integer("version").notNull().default(1),
    ...timestamps,
  },
  (t) => [
    index("grade_status_idx").on(t.status),
    check("grade_total_score_nonneg", sql`${t.totalScore} >= 0`),
    check("grade_version_positive", sql`${t.version} >= 1`),
  ],
);

export const criterionScore = pgTable(
  "criterion_score",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    gradeId: uuid("grade_id")
      .notNull()
      .references(() => grade.id, { onDelete: "cascade" }),
    criterionId: uuid("criterion_id")
      .notNull()
      .references(() => rubricCriterion.id, { onDelete: "restrict" }),
    levelId: uuid("level_id").references(() => rubricLevel.id, { onDelete: "restrict" }),
    points: integer("points").notNull().default(0),
    feedback: text("feedback").notNull().default(""),
    source: scoreSource("source").notNull(),
    aiConfidence: real("ai_confidence"),
    aiEvidence: jsonb("ai_evidence").$type<string[]>(),
    ...timestamps,
  },
  (t) => [
    uniqueIndex("criterion_score_grade_criterion_uq").on(t.gradeId, t.criterionId),
    check("criterion_score_points_range", sql`${t.points} between 0 and 100`),
    check(
      "criterion_score_confidence_range",
      sql`${t.aiConfidence} is null or ${t.aiConfidence} between 0 and 1`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Regrade requests
// ---------------------------------------------------------------------------

export const regradeRequest = pgTable(
  "regrade_request",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Unique: one regrade request per grade.
    gradeId: uuid("grade_id")
      .notNull()
      .unique()
      .references(() => grade.id, { onDelete: "cascade" }),
    studentId: text("student_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    criterionId: uuid("criterion_id").references(() => rubricCriterion.id, {
      onDelete: "restrict",
    }),
    reason: text("reason").notNull(),
    status: regradeStatus("status").notNull().default("OPEN"),
    response: text("response"),
    resolvedBy: text("resolved_by").references(() => user.id, { onDelete: "set null" }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    ...timestamps,
  },
  (t) => [index("regrade_request_status_idx").on(t.status)],
);

// ---------------------------------------------------------------------------
// Audit log
// ---------------------------------------------------------------------------

export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorId: text("actor_id").references(() => user.id, { onDelete: "set null" }),
    courseId: uuid("course_id").references(() => course.id, { onDelete: "cascade" }),
    action: varchar("action", { length: 64 }).notNull(),
    entityType: varchar("entity_type", { length: 32 }).notNull(),
    entityId: text("entity_id").notNull(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("audit_log_course_created_idx").on(t.courseId, t.createdAt),
    index("audit_log_entity_idx").on(t.entityType, t.entityId),
  ],
);

// ---------------------------------------------------------------------------
// Relations (for the Drizzle query API)
// ---------------------------------------------------------------------------

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  memberships: many(courseMember),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const courseRelations = relations(course, ({ one, many }) => ({
  creator: one(user, { fields: [course.createdBy], references: [user.id] }),
  members: many(courseMember),
  assignments: many(assignment),
}));

export const courseMemberRelations = relations(courseMember, ({ one }) => ({
  course: one(course, { fields: [courseMember.courseId], references: [course.id] }),
  user: one(user, { fields: [courseMember.userId], references: [user.id] }),
}));

export const assignmentRelations = relations(assignment, ({ one, many }) => ({
  course: one(course, { fields: [assignment.courseId], references: [course.id] }),
  criteria: many(rubricCriterion),
  submissions: many(submission),
}));

export const rubricCriterionRelations = relations(rubricCriterion, ({ one, many }) => ({
  assignment: one(assignment, {
    fields: [rubricCriterion.assignmentId],
    references: [assignment.id],
  }),
  levels: many(rubricLevel),
}));

export const rubricLevelRelations = relations(rubricLevel, ({ one }) => ({
  criterion: one(rubricCriterion, {
    fields: [rubricLevel.criterionId],
    references: [rubricCriterion.id],
  }),
}));

export const submissionRelations = relations(submission, ({ one, many }) => ({
  assignment: one(assignment, {
    fields: [submission.assignmentId],
    references: [assignment.id],
  }),
  student: one(user, { fields: [submission.studentId], references: [user.id] }),
  grade: one(grade),
  aiRuns: many(aiGradingRun),
}));

export const aiGradingRunRelations = relations(aiGradingRun, ({ one }) => ({
  submission: one(submission, {
    fields: [aiGradingRun.submissionId],
    references: [submission.id],
  }),
}));

export const gradeRelations = relations(grade, ({ one, many }) => ({
  submission: one(submission, { fields: [grade.submissionId], references: [submission.id] }),
  scores: many(criterionScore),
  regrade: one(regradeRequest),
}));

export const criterionScoreRelations = relations(criterionScore, ({ one }) => ({
  grade: one(grade, { fields: [criterionScore.gradeId], references: [grade.id] }),
  criterion: one(rubricCriterion, {
    fields: [criterionScore.criterionId],
    references: [rubricCriterion.id],
  }),
  level: one(rubricLevel, { fields: [criterionScore.levelId], references: [rubricLevel.id] }),
}));

export const regradeRequestRelations = relations(regradeRequest, ({ one }) => ({
  grade: one(grade, { fields: [regradeRequest.gradeId], references: [grade.id] }),
  student: one(user, { fields: [regradeRequest.studentId], references: [user.id] }),
}));
